name: de4js
title: de4js
description: JavaScript Deobfuscator and Unpacker
version: 1.6.0
author: Zzbaivong
author_email: Zzbaivong@gmail.com
url: https://lelinhtinh.github.io
baseurl: /de4js
repository: lelinhtinh/de4js
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-106940288-1
sass:
  style: compressed

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'package-lock.json']
incremental: false
